import Header from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins, Mouse_Memoirs } from 'next/font/google'
import Footer from '@/components/footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: "400",
})

export const mouse_memoirs = Mouse_Memoirs({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
